name: Clean Up Images

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  clean-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged images older than three days
        uses: snok/container-retention-policy@v1
        with:
          cut-off: Three days ago UTC
          account-type: org
          org-name: logto-io
          keep-at-least: 1
          untagged-only: true
          token: ${{ secrets.BOT_PAT }}
